spring.application.name=Youtube_Livechat_Project
server.port=8080
spring.config.import=optional:file:.env[.properties],optional:classpath:application-local.properties

# External tools
app.yt-dlp.path=${YT_DLP_PATH:yt-dlp}

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate SQL Log
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
